### ISSUE TITLE
Can't parse config file 'config.json'

### ISSUE THREAD

**Issue by tomclaessens** [fontello/fontello#578]
We never touched the config file manually and it has been working perfect up until 19/01 apparently (latest git commit in our repo)

This is the error which is visible in the browser console

`TypeError: Cannot read property 'selected' of undefined
    at s.removeGlyph (/assets/bundle-fontello.en-US-358a19c3731fc6e43b0dba29c5278349.js:77:3536)
    at /assets/bundle-fontello.en-US-358a19c3731fc6e43b0dba29c5278349.js:77:3502
    at Array.forEach (native)
    at s.removeGlyph (/assets/bundle-fontello.en-US-358a19c3731fc6e43b0dba29c5278349.js:77:3480)
    at a (/assets/bundle-fontello.en-US-358a19c3731fc6e43b0dba29c5278349.js:38:918)
    at FileReader.t.name.match.t.name.match.i.onload (/assets/bundle-fontello.en-US-358a19c3731fc6e43b0dba29c5278349.js:38:3914)`

Did our configuration file somehow got corrupted or is this a malfunction on the website?
Thanks.

[config.json.zip](https://github.com/fontello/fontello/files/729195/config.json.zip)

**Comment by tomclaessens** [comment]
Seems to be a temporary hickup because it's working now.
